### ISSUE TITLE
erreur Unable to import module 'lambda_function'

### ISSUE THREAD

**Issue by skaezer** [azerpas/nike-snkrs-pass-monitor#1]
Erreur lors du test de la fonction lambda sur aws : 

{

"errorMessage": "Unable to import module 'lambda_function': No module named 'lambda_function'",

"errorType": "Runtime.ImportModuleError",

"requestId": "b256388f-2bb3-408c-932c-4cfc57cfdb4c",

"stackTrace": []

}

runtime : Python 3.9

Handler : main.lambda_handler

**Comment by azerpas** [comment]
@skaezer probably has to do with the name of your AWS Lambda function (if you're running on AWS). [Check this out](https://stackoverflow.com/a/35355800/12440368)

```Error was due to file name of the lambda function. While creating the lambda function it will ask for Lambda function handler. You have to name it as your Python_File_Name.Method_Name. In this scenario I named it as lambda.lambda_handler (lambda.py is the file name). ```

![screenshot](https://i.stack.imgur.com/Ribcl.png)
